// This file contains the database schema data for the GAIA-QAO Object Identification System

export interface Column {
  name: string
  type: string
  isPrimaryKey: boolean
  isForeignKey: boolean
  isNullable: boolean
  default?: string
  description?: string
  references?: {
    table: string
    column: string
  }
}

export interface Index {
  name: string
  columns: string[]
  isUnique: boolean
}

export interface Table {
  name: string
  description: string
  category: string
  columns: Column[]
  indexes?: Index[]
  sqlDefinition: string
}

export interface Relationship {
  source: string
  target: string
  type: string
  sourceColumn?: string
  targetColumn?: string
}

export interface SchemaData {
  tables: Table[]
  relationships: Relationship[]
}

export const schemaData: SchemaData = {
  tables: [
    // Core ID Component Tables
    {
      name: "domains",
      description: "Stores domain definitions for the primary operational environment of aerospace objects",
      category: "core",
      columns: [
        {
          name: "domain_code",
          type: "CHAR(2)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - two-character domain code",
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Domain name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the domain",
        },
        {
          name: "altitude_boundary_meters",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Altitude boundary in meters for domain definition",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the domain is active",
        },
      ],
      sqlDefinition: `CREATE TABLE domains (
  domain_code CHAR(2) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  altitude_boundary_meters INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "autonomy_levels",
      description: "Stores autonomy level definitions indicating the degree of human involvement in system operation",
      category: "core",
      columns: [
        {
          name: "autonomy_code",
          type: "CHAR(1)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - single-character autonomy code",
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Autonomy level name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the autonomy level",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the autonomy level is active",
        },
      ],
      sqlDefinition: `CREATE TABLE autonomy_levels (
  autonomy_code CHAR(1) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "functional_classes",
      description: "Stores functional class definitions categorizing objects by their primary purpose or function",
      category: "core",
      columns: [
        {
          name: "class_code",
          type: "CHAR(3)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - three-character class code",
        },
        {
          name: "domain_code",
          type: "CHAR(2)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: false,
          description: "Foreign key to domains table",
          references: { table: "domains", column: "domain_code" },
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Functional class name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the functional class",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the functional class is active",
        },
      ],
      indexes: [{ name: "idx_functional_classes_domain", columns: ["domain_code"], isUnique: false }],
      sqlDefinition: `CREATE TABLE functional_classes (
  class_code CHAR(3) PRIMARY KEY,
  domain_code CHAR(2) NOT NULL REFERENCES domains(domain_code),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE(domain_code, class_code)
);`,
    },
    {
      name: "subtypes",
      description: "Stores sub-type definitions that further refine the classification within each functional class",
      category: "core",
      columns: [
        {
          name: "subtype_id",
          type: "SERIAL",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - auto-incrementing subtype ID",
        },
        {
          name: "subtype_code",
          type: "CHAR(2)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Two-character subtype code",
        },
        {
          name: "class_code",
          type: "CHAR(3)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: false,
          description: "Foreign key to functional_classes table",
          references: { table: "functional_classes", column: "class_code" },
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Sub-type name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the sub-type",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the sub-type is active",
        },
      ],
      indexes: [
        { name: "idx_subtypes_class", columns: ["class_code"], isUnique: false },
        { name: "idx_subtypes_unique_code", columns: ["class_code", "subtype_code"], isUnique: true },
      ],
      sqlDefinition: `CREATE TABLE subtypes (
  subtype_id SERIAL PRIMARY KEY,
  subtype_code CHAR(2) NOT NULL,
  class_code CHAR(3) NOT NULL REFERENCES functional_classes(class_code),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE(class_code, subtype_code)
);`,
    },
    {
      name: "model_series",
      description: "Reference table for standardized model series/generation codes",
      category: "reference",
      columns: [
        {
          name: "series_code",
          type: "CHAR(1)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - single-character series code",
        },
        {
          name: "name",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Series name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the series",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the series is active",
        },
      ],
      sqlDefinition: `CREATE TABLE model_series (
  series_code CHAR(1) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "model_size_categories",
      description: "Reference table for standardized model size category codes",
      category: "reference",
      columns: [
        {
          name: "size_code",
          type: "CHAR(1)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - single-character size code",
        },
        {
          name: "name",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Size category name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the size category",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the size category is active",
        },
      ],
      sqlDefinition: `CREATE TABLE model_size_categories (
  size_code CHAR(1) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "model_variant_types",
      description: "Reference table for standardized model variant type codes",
      category: "reference",
      columns: [
        {
          name: "variant_code",
          type: "CHAR(1)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - single-character variant code",
        },
        {
          name: "name",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Variant type name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the variant type",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the variant type is active",
        },
      ],
      sqlDefinition: `CREATE TABLE model_variant_types (
  variant_code CHAR(1) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "models",
      description: "Stores model/variant definitions representing specific designs within a sub-type",
      category: "core",
      columns: [
        {
          name: "model_id",
          type: "SERIAL",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - auto-incrementing model ID",
        },
        {
          name: "model_code",
          type: "CHAR(3)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Three-character model code",
        },
        {
          name: "subtype_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: false,
          description: "Foreign key to subtypes table",
          references: { table: "subtypes", column: "subtype_id" },
        },
        {
          name: "series_code",
          type: "CHAR(1)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to model_series table",
          references: { table: "model_series", column: "series_code" },
        },
        {
          name: "size_code",
          type: "CHAR(1)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to model_size_categories table",
          references: { table: "model_size_categories", column: "size_code" },
        },
        {
          name: "variant_code",
          type: "CHAR(1)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to model_variant_types table",
          references: { table: "model_variant_types", column: "variant_code" },
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Model name",
        },
        {
          name: "full_name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Full model name",
        },
        {
          name: "short_name",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Short model name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the model",
        },
        {
          name: "introduction_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the model was introduced",
        },
        {
          name: "end_of_production_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the model ended production",
        },
        {
          name: "model_status",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "'active'",
          description: "Status of the model (active, retired, etc.)",
        },
        {
          name: "certification_status",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Certification status of the model",
        },
        {
          name: "certification_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the model was certified",
        },
        {
          name: "manufacturer",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Manufacturer of the model",
        },
        {
          name: "technical_specifications",
          type: "JSONB",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Technical specifications in JSON format",
        },
        {
          name: "technical_specifications_schema",
          type: "JSONB",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "JSON Schema for technical specifications",
        },
        {
          name: "documentation_url",
          type: "VARCHAR(255)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "URL to model documentation",
        },
        {
          name: "model_image_url",
          type: "VARCHAR(255)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "URL to model image",
        },
        {
          name: "predecessor_model_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to models table (self-reference)",
          references: { table: "models", column: "model_id" },
        },
        {
          name: "successor_model_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to models table (self-reference)",
          references: { table: "models", column: "model_id" },
        },
        {
          name: "is_quantum_enhanced",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "FALSE",
          description: "Flag indicating if the model includes quantum-enhanced systems",
        },
        {
          name: "quantum_technologies",
          type: "JSONB",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "JSON array of quantum technologies implemented in this model",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the model is active",
        },
      ],
      indexes: [
        { name: "idx_models_subtype", columns: ["subtype_id"], isUnique: false },
        { name: "idx_models_model_code", columns: ["model_code"], isUnique: false },
        { name: "idx_models_series", columns: ["series_code"], isUnique: false },
        { name: "idx_models_quantum", columns: ["is_quantum_enhanced"], isUnique: false },
        { name: "idx_models_status", columns: ["model_status"], isUnique: false },
        { name: "idx_models_unique_code", columns: ["subtype_id", "model_code"], isUnique: true },
      ],
      sqlDefinition: `CREATE TABLE models (
  model_id SERIAL PRIMARY KEY,
  model_code CHAR(3) NOT NULL,
  subtype_id INT NOT NULL REFERENCES subtypes(subtype_id),
  series_code CHAR(1) REFERENCES model_series(series_code),
  size_code CHAR(1) REFERENCES model_size_categories(size_code),
  variant_code CHAR(1) REFERENCES model_variant_types(variant_code),
  name VARCHAR(100) NOT NULL,
  full_name VARCHAR(100),
  short_name VARCHAR(50),
  description TEXT,
  introduction_date DATE,
  end_of_production_date DATE,
  model_status VARCHAR(50) DEFAULT 'active',
  certification_status VARCHAR(50),
  certification_date DATE,
  manufacturer VARCHAR(100),
  technical_specifications JSONB,
  technical_specifications_schema JSONB,
  documentation_url VARCHAR(255),
  model_image_url VARCHAR(255),
  predecessor_model_id INT REFERENCES models(model_id),
  successor_model_id INT REFERENCES models(model_id),
  is_quantum_enhanced BOOLEAN DEFAULT FALSE,
  quantum_technologies JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE(subtype_id, model_code)
);`,
    },
    // Object Instances and Configurations
    {
      name: "object_instances",
      description: "Stores individual object instances with serial numbers",
      category: "instance",
      columns: [
        {
          name: "instance_id",
          type: "UUID",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          default: "uuid_generate_v4()",
          description: "Primary key - UUID for the instance",
        },
        {
          name: "model_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: false,
          description: "Foreign key to models table",
          references: { table: "models", column: "model_id" },
        },
        {
          name: "serial_number",
          type: "CHAR(5)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Five-character serial number",
        },
        {
          name: "full_object_id",
          type: "VARCHAR(30)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Complete DO-A-CCC-ST-MDL-SSSSS identifier",
        },
        {
          name: "manufacture_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the object was manufactured",
        },
        {
          name: "status",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "'active'",
          description: "Status of the object (active, retired, destroyed, etc.)",
        },
        {
          name: "owner_organization",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Organization that owns the object",
        },
        {
          name: "location_current",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Current location of the object",
        },
        {
          name: "commissioning_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the object was commissioned",
        },
        {
          name: "decommissioning_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the object was decommissioned",
        },
        {
          name: "notes",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Additional notes about the object",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
      ],
      indexes: [
        { name: "idx_object_instances_model", columns: ["model_id"], isUnique: false },
        { name: "idx_object_instances_serial", columns: ["serial_number"], isUnique: false },
        { name: "idx_object_instances_full_id", columns: ["full_object_id"], isUnique: true },
        { name: "idx_object_instances_status", columns: ["status"], isUnique: false },
        { name: "idx_object_instances_unique_serial", columns: ["model_id", "serial_number"], isUnique: true },
      ],
      sqlDefinition: `CREATE TABLE object_instances (
  instance_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  model_id INT NOT NULL REFERENCES models(model_id),
  serial_number CHAR(5) NOT NULL,
  full_object_id VARCHAR(30) NOT NULL,
  manufacture_date DATE,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  owner_organization VARCHAR(100),
  location_current VARCHAR(100),
  commissioning_date DATE,
  decommissioning_date DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(model_id, serial_number)
);`,
    },
    {
      name: "configuration_types",
      description: "Reference table for standardized configuration type codes",
      category: "reference",
      columns: [
        {
          name: "type_code",
          type: "CHAR(1)",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - single-character type code",
        },
        {
          name: "name",
          type: "VARCHAR(50)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Configuration type name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the configuration type",
        },
        {
          name: "domain_specific",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "FALSE",
          description: "Flag indicating if this configuration type is specific to a particular domain",
        },
        {
          name: "domain_code",
          type: "CHAR(2)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to domains table",
          references: { table: "domains", column: "domain_code" },
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the configuration type is active",
        },
      ],
      sqlDefinition: `CREATE TABLE configuration_types (
  type_code CHAR(1) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  domain_specific BOOLEAN DEFAULT FALSE,
  domain_code CHAR(2) REFERENCES domains(domain_code),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE
);`,
    },
    {
      name: "object_configurations",
      description: "Stores configuration variants for object instances",
      category: "config",
      columns: [
        {
          name: "configuration_id",
          type: "SERIAL",
          isPrimaryKey: true,
          isForeignKey: false,
          isNullable: false,
          description: "Primary key - auto-incrementing configuration ID",
        },
        {
          name: "instance_id",
          type: "UUID",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: false,
          description:
            'Foreign key to object  isPrimaryKey: false, isForeignKey: true, isNullable: false, description: "Foreign key to object_instances table',
          references: { table: "object_instances", column: "instance_id" },
        },
        {
          name: "configuration_code",
          type: "CHAR(2)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Two-character configuration code",
        },
        {
          name: "type_code",
          type: "CHAR(1)",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to configuration_types table",
          references: { table: "configuration_types", column: "type_code" },
        },
        {
          name: "version_number",
          type: "VARCHAR(10)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Version number for this configuration",
        },
        {
          name: "name",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Configuration name",
        },
        {
          name: "description",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Detailed description of the configuration",
        },
        {
          name: "effective_from",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          description: "Date from which this configuration is effective",
        },
        {
          name: "effective_to",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date until which this configuration is effective",
        },
        {
          name: "supersedes_configuration_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to object_configurations table (self-reference)",
          references: { table: "object_configurations", column: "configuration_id" },
        },
        {
          name: "superseded_by_configuration_id",
          type: "INT",
          isPrimaryKey: false,
          isForeignKey: true,
          isNullable: true,
          description: "Foreign key to object_configurations table (self-reference)",
          references: { table: "object_configurations", column: "configuration_id" },
        },
        {
          name: "certification_reference",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Reference to certification documentation",
        },
        {
          name: "certification_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date the configuration was certified",
        },
        {
          name: "change_reason",
          type: "TEXT",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Reason for the configuration change",
        },
        {
          name: "change_authority",
          type: "VARCHAR(100)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Authority that approved the change",
        },
        {
          name: "documentation_url",
          type: "VARCHAR(255)",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "URL to configuration documentation",
        },
        {
          name: "is_temporary",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "FALSE",
          description: "Flag indicating if this is a temporary configuration",
        },
        {
          name: "reversion_date",
          type: "DATE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Date when a temporary configuration will revert",
        },
        {
          name: "configuration_details",
          type: "JSONB",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: true,
          description: "Configuration details in JSON format",
        },
        {
          name: "created_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record creation timestamp",
        },
        {
          name: "updated_at",
          type: "TIMESTAMP WITH TIME ZONE",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "CURRENT_TIMESTAMP",
          description: "Record update timestamp",
        },
        {
          name: "is_active",
          type: "BOOLEAN",
          isPrimaryKey: false,
          isForeignKey: false,
          isNullable: false,
          default: "TRUE",
          description: "Flag indicating if the configuration is active",
        },
      ],
      indexes: [
        { name: "idx_config_instance", columns: ["instance_id"], isUnique: false },
        { name: "idx_config_code", columns: ["configuration_code"], isUnique: false },
        { name: "idx_config_type", columns: ["type_code"], isUnique: false },
        { name: "idx_config_dates", columns: ["effective_from", "effective_to"], isUnique: false },
        { name: "idx_config_active", columns: ["is_active"], isUnique: false },
        { name: "idx_config_unique", columns: ["instance_id", "configuration_code", "effective_from"], isUnique: true },
      ],
      sqlDefinition: `CREATE TABLE object_configurations (
  configuration_id SERIAL PRIMARY KEY,
  instance_id UUID NOT NULL REFERENCES object_instances(instance_id),
  configuration_code CHAR(2) NOT NULL,
  type_code CHAR(1) REFERENCES configuration_types(type_code),
  version_number VARCHAR(10),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  effective_from DATE NOT NULL,
  effective_to DATE,
  supersedes_configuration_id INT REFERENCES object_configurations(configuration_id),
  superseded_by_configuration_id INT REFERENCES object_configurations(configuration_id),
  certification_reference VARCHAR(100),
  certification_date DATE,
  change_reason TEXT,
  change_authority VARCHAR(100),
  documentation_url VARCHAR(255),
  is_temporary BOOLEAN DEFAULT FALSE,
  reversion_date DATE,
  configuration_details JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE(instance_id, configuration_code, effective_from)
);`,
    },
    // Additional tables would continue here...
  ],
  relationships: [
    // Core ID Component Relationships
    { source: "domains", target: "functional_classes", type: "has" },
    { source: "functional_classes", target: "subtypes", type: "has" },
    { source: "subtypes", target: "models", type: "has" },
    { source: "model_series", target: "models", type: "has" },
    { source: "model_size_categories", target: "models", type: "has" },
    { source: "model_variant_types", target: "models", type: "has" },
    { source: "models", target: "models", type: "predecessor_successor" },
    { source: "subtypes", target: "model_specification_templates", type: "has" },

    // Object Instances and Configurations Relationships
    { source: "models", target: "object_instances", type: "has" },
    { source: "object_instances", target: "object_configurations", type: "has" },
    { source: "configuration_types", target: "object_configurations", type: "has" },
    { source: "object_configurations", target: "object_configurations", type: "supersedes" },
    { source: "domains", target: "configuration_types", type: "has_domain_specific" },

    // Additional relationships would continue here...
  ],
}
