# SLSA Provenance Workflow
# Purpose: Generate SLSA Level 3 provenance for project artifacts.
# Usage: Trigger manually or on release creation.
# Limitations: Requires integration with downstream verification tools.

name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}
    permissions:
      actions: none
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Replace with commit SHA if possible

      - name: Build artifacts
        run: |
          # Replace with actual build commands
          make build
          cp output/binary1 artifact1
          cp output/binary2 artifact2

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          files=$(ls artifact*)
          for file in $files; do
            [ -f "$file" ] || { echo "Invalid file: $file"; exit 1; }
          done
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true

  notify:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify stakeholders
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "SLSA Provenance Workflow Failed"}' <notification-endpoint>
